robot_cameras:
  floor_robot_camera: 
    active: true
    type: rgb
  
  ceiling_robot_camera: 
    active: true
    type: rgbd

static_sensors:
  bin1_camera:
    type: advanced_logical_camera
    pose:
      xyz: [0.27, -2.325, 1.8]
      rpy: [pi, pi/2, 0]

  bin2_camera:
    type: advanced_logical_camera
    pose:
      xyz: [0.27, 2.8, 1.8]
      rpy: [pi, pi/2, 0]
  
  conveyor_breakbeam:
    type: break_beam
    pose:
      xyz: [-0.352, 3.91, 0.88]
      rpy: [0, 0, pi]
  
  conveyor_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-0.573, 3.915, 1.8]
      rpy: [pi/2, pi/2, 0]